//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by HackIt.rc
//
#define ID_NOFUNCTIONS                  0
#define AF_AUTOTOP                      1
#define IDD_CAPTURE                     1
#define AF_AUTOHIDE                     2
#define AF_AUTOTRAY                     4
#define AF_AUTOMIN                      8
#define IDM_ABOUTBOX                    0x0010
#define AF_AUTOMAX                      16
#define IDM_CLOSEAPP                    0x0020
#define AF_AUTOCLOSE                    32
#define AF_AUTOKILL                     64
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_HACKIT4_DIALOG              102
#define IDS_CLOSEAPP                    102
#define AF_AUTOPRIORITY                 128
#define IDR_MAINFRAME                   128
#define IDI_DESKTOP                     129
#define IDI_HIDDEN                      130
#define IDR_MENU1                       134
#define IDR_MAINMENU                    134
#define IDD_WINDOWINFO                  139
#define IDR_MAINFRAMESM                 141
#define IDD_AUTO                        142
#define IDR_ACCELERATOR1                144
#define IDI_DEFAULT                     145
#define IDB_BITMAP1                     150
#define IDR_MENU2                       152
#define IDR_WAVE1                       156
#define IDR_POPUP                       158
#define IDI_TRAY                        159
#define IDI_TOPPED                      160
#define IDB_HIGH_CHECKED                165
#define IDB_NORMAL_CHECKED              166
#define IDB_IDLE_CHECKED                167
#define IDB_REALTIME_CHECKED            170
#define IDD_AUTOENTRY                   175
#define IDD_DIALOG1                     177
#define IDD_TEXTENTRY                   177
#define IDI_BUTTON                      179
#define IDI_STATIC                      180
#define IDI_EDIT                        181
#define IDI_COMBO                       182
#define IDI_SCROLL                      183
#define IDI_LIST                        184
#define IDI_TREEVIEW                    185
#define IDI_LISTVIEW                    186
#define IDI_TABCTRL                     187
#define IDR_BUTTONMENU                  190
#define IDR_WINDOWMENU                  191
#define IDR_PROCESSMENU                 193
#define IDR_EDITMENU                    194
#define IDR_SCROLLBARMENU               195
#define IDR_LISTVIEWMENU                197
#define IDD_ILLEGALWINDOWDLG            198
#define IDD_ILLEGALWINDOWENTRY          199
#define IDD_SPLASH                      201
#define IDB_SPLASH                      203
#define IDD_SETTINGS_WINDOWS            204
#define IDD_SETTINGS_GENERAL            205
#define IDD_SETTINGS                    206
#define IDI_TOOLTIP                     213
#define IDI_STATUS                      214
#define IDI_MDICLIENT                   215
#define IDI_DIALOG                      216
#define IDI_TOOLBAR                     217
#define IDR_TRANSPARENCY                218
#define AF_AUTOIDLE                     256
#define AF_AUTONORMAL                   512
#define IDC_TREE1                       1000
#define IDC_STATUS                      1006
#define IDC_CLASSINFO                   1006
#define IDC_AUTOSPECS                   1021
#define IDC_AUTOENTRIES                 1021
#define IDC_ADDITEM                     1022
#define IDC_DELETEITEM                  1023
#define AF_AUTOHIGH                     1024
#define IDC_AUTOTOP                     1024
#define IDC_AUTOHIDE                    1025
#define IDC_AUTOTRAY                    1026
#define IDC_SPECEDIT                    1027
#define IDC_AUTOMIN                     1035
#define IDC_AUTOMAX                     1036
#define IDC_AUTOKILL                    1037
#define IDC_AUTOCLOSE                   1039
#define IDC_AUTOPRIORITY                1040
#define IDC_CASESENSE                   1042
#define IDC_OPTIONS                     1049
#define IDC_SCRIPTING                   1050
#define IDC_AUTONONE                    1051
#define IDC_WINDOWFUNCS                 1052
#define IDC_EDITITEM                    1053
#define IDC_SCRIPT                      1055
#define IDC_SCRIPT_EDIT                 1055
#define IDC_OPTIONSGROUP                1056
#define IDC_INFOEDIT                    1081
#define IDC_FILENAME_EDIT               1084
#define IDC_WINDOWTITLE_EDIT            1088
#define IDC_WINDOWCLASS_EDIT            1090
#define IDC_ENTRYNAME                   1091
#define IDC_TAB1                        1093
#define IDC_SETTINGSTABS                1093
#define IDC_CHECK                       1095
#define IDC_TEXTENTRY                   1098
#define IDC_HANDLEINFO                  1099
#define IDC_STATUSBAR                   1100
#define IDC_ADDILLEGALWINDOW            1102
#define IDC_DELETEILLEGALWINDOW         1103
#define IDC_EDITILLEGALWINDOW           1104
#define IDC_ILLEGALWINDOWDROPBOX        1106
#define IDC_ILLEGALTEXTEDIT             1107
#define IDC_ILLEGALWINDOWLIST           1108
#define IDC_CHILDREN                    1120
#define IDC_TITLELESS                   1121
#define IDC_ILLEGAL                     1123
#define IDC_TIMED                       1128
#define IDC_PERSISTANT                  1129
#define IDC_MANUAL                      1130
#define IDC_EDIT2                       1132
#define IDC_DELAY                       1132
#define IDC_RESIZEHEIGHT                1132
#define IDC_WINDOW_TITLE                1132
#define IDC_WINDOWLISTCLEANERTIME       1132
#define IDC_SPIN1                       1133
#define IDC_DELAYSPIN                   1133
#define IDC_WIDTHSPIN                   1133
#define IDC_HACKITTRANSPARENT_SPIN      1133
#define IDC_TEXT                        1135
#define IDC_REFRESHTEXT                 1135
#define IDC_EDIT3                       1136
#define IDC_WINDOW_CLASS                1136
#define IDC_HIDESTART                   1137
#define IDC_HIDEONSTART                 1137
#define IDC_FONT                        1138
#define IDC_SHOWSPLASH                  1139
#define IDC_AUTOFUNCTIONSENABLED        1141
#define IDC_CHILDFUNCTIONSENABLED       1142
#define IDC_COMBO1                      1143
#define IDC_WINDOWCOMBO                 1143
#define IDC_COMBO2                      1144
#define IDC_TOPMOSTCOMBO                1144
#define IDC_COMBO3                      1145
#define IDC_VISIBILITYCOMBO             1145
#define IDC_COMBO4                      1146
#define IDC_PRIORITYCOMBO               1146
#define IDC_CHECK1                      1147
#define IDC_TOPCHECK                    1147
#define IDC_SYSMENUCHECK                1147
#define IDC_ILLEGALCASESENSITIVE        1147
#define IDC_HACKITTRANSPARENT           1147
#define IDC_CHECK2                      1148
#define IDC_TRAYCHECK                   1148
#define IDC_HACKITONTOP                 1148
#define IDC_SYSMENUVISIBLE              1148
#define IDC_COMBO5                      1150
#define IDC_DESTRUCTIONCOMBO            1150
#define IDC_EDIT1                       1151
#define IDC_RESIZEWIDTH                 1151
#define IDC_WINDOW_HANDLE               1151
#define IDC_CONSOLEPOLLINGTIME          1151
#define IDC_ILLEGALNAME                 1151
#define IDC_HACKITTRANSPARENT_PERCENT   1151
#define IDC_SPIN2                       1153
#define IDC_HEIGHTSPIN                  1153
#define IDC_SPIN3                       1155
#define IDC_XSPIN                       1155
#define IDC_EDIT5                       1157
#define IDC_MOVEY                       1157
#define IDC_WINDOW_PROCESSID            1157
#define IDC_SPIN5                       1158
#define IDC_YSPIN                       1158
#define IDC_MOVEX                       1159
#define IDC_SPECIALCOMBO                1160
#define IDC_ALTERNATECOMBO              1161
#define IDC_ALTERNATETEXT               1163
#define IDC_SPECIALTEXT                 1164
#define IDC_RESIZECHECK                 1168
#define IDC_MOVECHECK                   1169
#define IDC_TITLECOMBO                  1170
#define IDC_CLASSCOMBO                  1171
#define IDC_FILENAMECOMBO               1172
#define IDC_HIGHESTPRIORITY             1173
#define IDC_HIGHPRIORITY                1174
#define IDC_NORMALPRIORITY              1175
#define IDC_LOWPRIORITY                 1176
#define IDC_SYSMENUTOPPED               1180
#define IDC_SYSMENUTRAYYED              1181
#define IDC_SYSMENU_PRIORITY            1182
#define IDC_SYSMENUPRIORITY             1182
#define IDC_TOPMOSTCHILDREN             1183
#define IDC_UPDATEADDREMOVE             1184
#define IDC_UPDATEAUTO                  1185
#define IDC_CASESENSITIVE               1186
#define IDC_EDIT4                       1187
#define IDC_WINDOW_EXECUTABLE           1187
#define IDC_EDIT6                       1188
#define IDC_WINDOW_PROCESSPRIORITY      1188
#define IDC_EDIT7                       1189
#define IDC_EDIT8                       1190
#define IDC_WINDOW_RESTOREDPOSITION     1190
#define IDC_EDIT9                       1191
#define IDC_WINDOW_RESTOREDSIZE         1191
#define IDC_NAMELESSTEXT                1198
#define IDC_CONSOLEPOLL                 1199
#define IDC_CLEANLIST                   1201
#define IDC_ILLEGALFILENAMECOMBO        1202
#define IDC_ILLEGALTITLECOMBO           1203
#define IDC_ILLEGALCLASSCOMBO           1204
#define IDC_SYSMENUTRANSPARENCY         1206
#define IDC_TRANSPARENCYCOMBO           1207
#define IDC_TRANSPARENCYSTATIC          1208
#define IDC_TRANSPARENCYPERCENTSTATIC   1209
#define IDC_SYSMENU_APPEND              1210
#define IDC_USELARGEICONS               1211
#define IDC_WINDOWICONFIRST             1212
#define AF_AUTOREALTIME                 2048
#define ID_ICON_PASTE                   32777
#define ID_TITLEBAR_COPY                32778
#define ID_TITLEBAR_PASTE               32779
#define ID_TITLEBAR_ERASE               32780
#define ID_TITLEBAR_EDIT                32781
#define ID_ICON_ERASE                   32782
#define ID_ICON_EDIT                    32783
#define ID_ICON_COPY                    32800
#define ID_LIST_REFRESH                 32802
#define ID_REFRESH                      32802
#define ID_LIST_SHOWCHILDREN            32803
#define ID_SHOWCHILDREN                 32803
#define ID_SHOWFUNKY                    32804
#define ID_OTHER_AUTOFUNC               32811
#define ID_AUTOFUNCS                    32811
#define ID_HELP_COMINGSOON              32812
#define ID_HELP_PLEASEDONATE            32813
#define ID_HELP_PLEASEREGISTER          32813
#define ID_HIDESHOWMAIN                 32817
#define ID_OTHER_HIDEONSTART            32819
#define ID_TEST                         32820
#define ID_VISIBLE                      32822
#define ID_VISIBLEHIDDEN                32822
#define ID_HIDDEN                       32823
#define ID_TOPPED                       32824
#define ID_TOPPEDUNTOPPED               32824
#define ID_UNTOPPED                     32825
#define ID_MINIMIZE                     32831
#define ID_MAXIMIZE                     32832
#define ID_RESTORE                      32833
#define ID_CLOSE                        32834
#define ID_ENDTASK                      32835
#define ID_TRAYYEDUNTRAYYED             32836
#define ID_OTHER_SAVENOW                32839
#define ID_OTHER_PERSISTANTREFRESHING   32840
#define ID_OTHER_TEXTANDICONREFRESHING  32841
#define ID_UPDATE_TOGGLE                32841
#define ID_TESTING_PRESSBUTTON          32842
#define ID_TESTING_TEST                 32843
#define ID_SETFONT                      32844
#define ID_ABOUT                        32845
#define ID_BUTTON_PRESS                 32848
#define ID_WINDOW_DISABLED              32852
#define ID_PROCESS_REALTIME             32853
#define ID_PROCESS_HIGH                 32854
#define ID_PROCESS_NORMAL               32855
#define ID_PROCESS_IDLE                 32856
#define ID_PROCESS_ENDTASK              32857
#define ID_EDIT_PASSWORDMASK            32860
#define ID_SCROLLBAR_UP                 32863
#define ID_SCROLLBAR_DOWN               32864
#define ID_SCROLLBAR_PAGEUP             32865
#define ID_SCROLLBAR_PAGEDOWN           32866
#define ID_SCROLLBAR_ABSOLUTE           32867
#define ID_WINDOW_SETFONT               32868
#define ID_LISTVIEW_LARGE               32869
#define ID_LISTVIEW_SMALL               32870
#define ID_LISTVIEW_LIST                32871
#define ID_LISTVIEW_DETAILS             32872
#define ID_SETTINGS_REFRESHSPEED_PERSISTANT 32873
#define ID_SETTINGS_REFRESHSPEED_1SECOND 32874
#define ID_SETTINGS_REFRESHSPEED_2SECONDS 32875
#define ID_SETTINGS_REFRESHSPEED_5SECONDS 32876
#define ID_SETTINGS_REFRESHSPEED_10SECONDS 32877
#define ID_SETTINGS_REFRESHSPEED_MANUAL 32878
#define ID_SETTINGS_REFRESHSPEED_REFRESH 32879
#define ID_SETTINGS_ILLEGALWINDOWS      32880
#define ID_SHOWSPLASH                   32881
#define ID_SETTINGS                     32882
#define ID_LOGGING                      32883
#define ID_WINDOWINFO                   32884
#define ID_TRANSPARENCY_NONE            32886
#define ID_TRANSPARENCY_10              32887
#define ID_TRANSPARENCY_20              32888
#define ID_TRANSPARENCY_30              32889
#define ID_TRANSPARENCY_40              32890
#define ID_TRANSPARENCY_50              32891
#define ID_TRANSPARENCY_60              32892
#define ID_TRANSPARENCY_70              32893
#define ID_TRANSPARENCY_80              32894
#define ID_TRANSPARENCY_90              32895
#define ID_TRANSPARENCY_100             32896
#define IDM_VISIBLEHIDDEN               0x9030
#define IDM_TOPPEDUNTOPPED              0x9040
#define IDM_TRAYYEDUNTRAYYED            0x9050
#define IDM_HIGHESTPRIORITY             0x9060
#define IDM_HIGHPRIORITY                0x9070
#define IDM_NORMALPRIORITY              0x9080
#define IDM_LOWPRIORITY                 0x9090
#define IDM_TRANSPARENCY_20             0x9110
#define IDM_TRANSPARENCY_30             0x9120
#define IDM_TRANSPARENCY_40             0x9130
#define IDM_TRANSPARENCY_50             0x9140
#define IDM_TRANSPARENCY_60             0x9150
#define IDM_TRANSPARENCY_70             0x9160
#define IDM_TRANSPARENCY_80             0x9170
#define IDM_TRANSPARENCY_90             0x9180
#define IDM_TRANSPARENCY_100            0x9190
#define IDM_TRANSPARENCY_NONE           0x9210
#define IDM_TRANSPARENCY_10             0x9220
#define ID_HELP_TOPICS                  57666
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        221
#define _APS_NEXT_COMMAND_VALUE         32898
#define _APS_NEXT_CONTROL_VALUE         1213
#define _APS_NEXT_SYMED_VALUE           105
#endif
#endif
